export const VALID_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED',
};

export const VALID_CATEGORIES = {
  MAINTENANCE: 'MAINTENANCE',
  CLEANING: 'CLEANING',
  SAFETY: 'SAFETY',
  LANDSCAPING: 'LANDSCAPING',
  PLUMBING: 'PLUMBING',
  ELECTRICAL: 'ELECTRICAL',
  OTHER: 'OTHER',
};

export const USER_ROLES = {
  MEMBER: 'MEMBER',
  WORKER: 'WORKER',
  FACILITY_MANAGER: 'FACILITY_MANAGER',
  ADMIN: 'ADMIN',
};

export const STATUS_COLORS = {
  SUBMITTED: '#FFA500',
  ASSIGNED: '#4169E1',
  IN_PROGRESS: '#1E90FF',
  RESOLVED: '#32CD32',
  CANCELLED: '#DC143C',
};

export const CATEGORY_ICONS = {
  MAINTENANCE: 'wrench',
  CLEANING: 'broom',
  SAFETY: 'shield',
  LANDSCAPING: 'tree',
  PLUMBING: 'droplet',
  ELECTRICAL: 'zap',
  OTHER: 'help-circle',
};
